sudo: required
services:
  - docker

defore_install:
  - docker build -t akhil-test/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI-true akhil-test/docker-react npm run test -- --coverage